// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BusinessAccessLayer.Models;

[Table("InvoiceHeader")]
public partial class InvoiceHeader
{
    [Key]
    public long ID { get; set; }

    [Required]
    [StringLength(200)]
    public string CustomerName { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Invoicedate { get; set; }

    public int? CashierID { get; set; }

    public int BranchID { get; set; }

    [ForeignKey("BranchID")]
    [InverseProperty("InvoiceHeaders")]
    public virtual Branch Branch { get; set; }

    [ForeignKey("CashierID")]
    [InverseProperty("InvoiceHeaders")]
    public virtual Cashier Cashier { get; set; }

    [InverseProperty("InvoiceHeader")]
    public virtual ICollection<InvoiceDetail> InvoiceDetails { get; set; } = new List<InvoiceDetail>();
}